package com.nseit.payment.models;

import java.io.InputStream;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import com.nseit.generic.models.CommonBean;

import lombok.Getter;
import lombok.Setter;

@Getter
@Setter
public class PaymentOnlineBean {
	private String netBankingBankName;
	private String creditCardBankName;
	private String netBankingAmount;
	private String registrationNumber;
	private Integer creditCardAmount;
	private Integer accountNumber;
	private String cardType;
	private Integer cardNumber;
	private List<OesBankMaster> bankList;
	private String createdBy;
	private String paymentPK;
	private Long userFK;
	private String paymentModeOnline;
	private String paymentStartDate;
	private String paymentEndDate;
	private String displayPaymentFlag;
	private String displayRegFlag;
	private String otbsDisplayFlag;
	private String transactionNumber;
	private String errMsg;
	private String bankID;
	private String bankName;
	private InputStream bankLogoImage;
	private String paymentModeDD;
	private String paymentModeCH;
	private String transactionDate;
	private String transactionNo;
	private String bid;
	private String itc;
	private String currency;
	private String amount;
	private String stage;
	private String createdDate;
	private String checkStatusDate;
	private String bank_fk;
	private String ddChallanReceiptNo;
	private int disciplineId;
	private String ddDate;
	private String ddBankCode;
	private String ddCityName;
	private String ddNumber;
	private String ePostPaymentDate;
	private String ePostCityCode;
	private String ePostCode;
	private String ePostBranchName;
	private String ePostBranchCode;
	private String epost;
	private String ePostFeesAmount;
	private String scrollNumber;
	private String challanDate;
	private String challanCityCode;
	private String challanBankCode;
	private String submitVal = "";
	private String challanBranchName;
	private String challanBranchCode;
	private String challanFeesAmount;
	private List<CommonBean> challanBankList;
	private PaymentOnlineBean ddpaymentBean;
	private PaymentOnlineBean challanpaymentBean;
	private PaymentOnlineBean onlinePaymentBean;
	private String paymentDisplayFlag;
	private List<CommonBean> cityList;
	private String PRN;
	private String AMT;
	private String Bank;
	private String BID;
	private String EEDID;
	private String PAID;
	private String paymentModeType;
	private Map<Integer, String> paymentModeList = new LinkedHashMap<Integer, String>();
	private String msg;
	private String job;
	private String applicationNum;
	private String disciplineDesc;
	private String testFK;
	private List<PaymentOnlineBean> candidateAppliedCourseList;
	private Map<Integer, String> appliedCourseList = new LinkedHashMap<Integer, String>();
	private String jobPaymentFlag;
	private String jobPaymentMsg;
	private String opd_app_no;
	private String opd_user_fk;
	private String opd_transaction_date;
	private String opd_transaction_no;
	private String opd_created_by;
	private String opd_test_fk;
	private String opd_mobile_no;
	private String opd_email_id;
	private String opd_validated_status;
	private String sucMsg;
	private String ShowModuleDetails;
	private String errMsgSingle;
	private String opd_sub_test_fk;
	private String opd_table_check;
	private String fees;
	private String applicantName;
	private String applicantDob;
	private String applicantMobile;
	private String paymentStatus;
	private boolean reconcile;
	private String enableButton;
	private String authStatus;
	private String transactionMessage;
	private String errorDescription;
	private String customerId;
	private String txnReferenceNo;
	private String txnAmount;
	private String txnDate;
	private String responseOFlag;
	private String userId;
	private String applicationNo;
	private String mobileNo;
	private String updatedtrnxDate;
	private String di1;
	private String di2;
	private String di3;
	private String post1;
	private String post2;
	private String orderID;
	private String txnscamt;
	private String clientCode;
	private String txnid;
	private String custacc;
	private String responseURL;
	private String signature;
	private String requestHashKey;
	private String requestURL;
	private String respHashKey;
	private String vendorID;
	private String ttype;
	private String prodid;
	private String txncurr;
	private String password;
	private String udf1;
	private String udf2;
	private String udf3;
	private String udf9;
	private String udf21;
	private String aiPayToken;
	private String environment;
	private String merchantId;
	private String returnUrl;
	private String emailID;
}
