package com.nseit.generic.queries;

// Settings related generic queries added by Tarka on 03-Jan-2012
public interface SettingsQueries
{
					/** SELECT STATEMENTS FOR ADMIN QUERIES **/
	String GET_TEST_DATES = " SELECT datewindow.ODW_DATE_WINDOW_PK, datewindow.ODW_START_DATE, " +
			" datewindow.ODW_END_DATE " +
			" FROM OES_date_window datewindow " +
			" order by datewindow.ODW_DATE_WINDOW_PK ";
	
	
	String GET_ACTIVITY_DETAILS = " select OCP_KEY_VALUE "+
		" from OES_CONFIG_PARAMETER "+
		" where OCP_KEY_NAME = ? ";
	
	String GET_EMAIL_SMS_DETAILS = " SELECT OSEM_TEST_FK, OSEM_ACTIVITY_FK, OSEM_MAIL_OBJECT, OSEM_SMS_OBJECT, "+
	" OSEM_SUBJECT, OSEM_CC_ADDRESS, OSEM_MAIL_APPLICABLE	, OSEM_SMS_APPLICABLE "+
	" FROM OES_SMS_EMAIL_MASTER "+
	" WHERE OSEM_TEST_FK = ? and OSEM_ACTIVITY_FK = ? ";
	
	String INSERT_EMAIL_SMS_DETAILS =
		" insert into OES_SMS_EMAIL_MASTER (OSEM_SMS_EMAIL_PK,OSEM_TEST_FK," +
		"OSEM_ACTIVITY_FK,OSEM_MAIL_OBJECT,OSEM_SMS_OBJECT ,OSEM_SUBJECT, "+
			" OSEM_CC_ADDRESS,OSEM_MAIL_APPLICABLE,OSEM_SMS_APPLICABLE," +
			"OSEM_STATUS, OSEM_CREATED_BY,OSEM_CREATED_DATE) "+
		" values(nextval('OES_SMS_EMAIL_MASTER_SEQ'),?,?,?,?,?,?,?,?,'A',?,CURRENT_TIMESTAMP) ";
	
	
	String UPDATE_DATE_RANGES = " update OES_date_window set ODW_START_DATE = ?, ODW_END_DATE = ?," +
			" ODW_UPDATED_BY = ?, ODW_UPDATED_DATE = CURRENT_TIMESTAMP where ODW_DATE_WINDOW_PK = ? ";
	
	
	String UPDATE_EMAIL_SMS_DETAILS =
		" update OES_SMS_EMAIL_MASTER set "+
			" OSEM_ACTIVITY_FK=?,OSEM_MAIL_OBJECT=?,OSEM_SMS_OBJECT=?,OSEM_SUBJECT=?," +
			" OSEM_CC_ADDRESS=?,OSEM_MAIL_APPLICABLE=?,OSEM_SMS_APPLICABLE=?  ,OSEM_UPDATED_BY =?,"+
		" OSEM_UPDATED_DATE=CURRENT_TIMESTAMP "+
		" where OSEM_TEST_FK=? and OSEM_ACTIVITY_FK=?";
	
	String UPDATE_TRAINING_DETAILS_UPLOAD =
		"update OES_CONFIG_PATHS set " +
		"	OCPT_PATH_VALUE =?,OCPT_UPDATED_BY =?, " +
		"	OCPT_UPDATED_DATE=systimestamp where OCPT_PATH_NAME=?";  

}
